version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: payhere
      MYSQL_ROOT_PASSWORD: password
      TZ: Asia/Seoul
    ports:
      - 3309:3306
    volumes:
      - ./db/mysql/data:/var/lib/mysql