spring:
  datasource:
    url: jdbc:mysql://localhost:3309/payhere?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  header: Authorization
  secret: and0LXRva2VuLXBheWhlcmUtcHJvY2Vzcy1qd3QtdG9rZW4tcGF5aGVyZS1wcm9jZXNzLWp3dC10b2tlbi1wYXloZXJlLXByb2Nlc3Mtand0LXRva2VuLXBheWhlcmUtcHJvY2Vzcy0=
  token-validity-in-seconds: 86400

springdoc:
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
  paths-to-match:
    - /**

